import{S as f,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function d(n,r){const o="https://pixabay.com/api/",i={key:r,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0},e=new URLSearchParams(i).toString(),t=`${o}?${e}`;return fetch(t).then(s=>{if(!s.ok)throw new Error(`HTTP error! status: ${s.status}`);return s.json()})}function m(n){return n.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-link">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        <ul class="image-info">
          <li>Likes <span>${r.likes}</span></li>
          <li>Views <span>${r.views}</span></li>
          <li>Comments <span>${r.comments}</span></li>
          <li>Downloads <span>${r.downloads}</span></li>
        </ul>
      </a>`).join("")}const c=document.querySelector("#search-form"),u=document.querySelector("#loader"),a=document.querySelector("#gallery"),p="48131456-02178b54d24f02562d64ec2d5",h=new f(".gallery-link",{captionsData:"alt",captionDelay:250});c.addEventListener("submit",n=>{n.preventDefault(),a.innerHTML="";const r=n.currentTarget.elements.searchQuery.value.trim();if(!r){l.warning({message:"Please enter a search query!",position:"topRight",timeout:3e3}),a.innerHTML="",c.reset();return}u.classList.remove("hidden"),d(r,p).then(o=>{if(o.hits.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}),a.innerHTML="",c.reset();return}const i=m(o.hits);a.innerHTML=i,console.log(o),h.refresh()}).catch(o=>{l.error({message:`An error occurred: ${o.message}`,position:"topRight",timeout:3e3})}).finally(()=>{u.classList.add("hidden")})});
//# sourceMappingURL=index.js.map
